### ISSUE TITLE
Scan ports on IP addresses other than 0.0.0.0?

### ISSUE THREAD

**Issue by emk** [notkild/port_scanner-rs#1]
Thank you for releasing this as a Rust library! It's simple but very useful. However, I have a feature proposal. 🙂

When working with Docker, it's normal to have multiple containers on your system, each with it's own network address. These containers are often started asynchronously, and it takes them a while to make a port available. In the [cage](http://cage.faraday.io/) tool, I need to poll containers to see if they have an open port. Ideally, it would have a `ToSocketAddrs` argument like `bind`: `bind<A: ToSocketAddrs>(addr: A)`.

Would you be interested in supporting this feature in your library? I could send you a PR.

**Comment by babariviere** [comment]
I have added two functions to fulfill your request. I hope this is what you expect 😄

**Comment by emk** [comment]
Looks great! Thank you very much.

Le 25 oct. 2016 7:25 PM, "Bastien Rivière" notifications@github.com a
écrit :
