### ISSUE TITLE
Trouble with port_scanner::scan_port

### ISSUE THREAD

**Issue by hutch** [notkild/port_scanner-rs#2]
Hi,

I'm having new difficulties with port_scanner::scan_port after upgrading from v1.5 from v1.2 on OS X 10.11, and I can't go back to 1.2 because you've yanked it from crates.io (there's other ways to do this but I don't want to go there yet)

scan_port is always returning false.

I'm kinda at a loss beyond that.

Cheers,
Bob

**Comment by hutch** [comment]
Actually, the local versions you've added work.

Is this expected?

**Comment by babariviere** [comment]
If you scan port of localhost, you will need to use other functions provided.
So it only depend on what you want to do.
If you want to scan a local port, use `local_port_available` else use `scan_port`.
If you want more detail, just tell me :smile:

**Comment by babariviere** [comment]
And I have yanked my packages because the functions were not supposed to scan local port but remote port

**Comment by hutch** [comment]
Maybe be a little more explicit in the old methods about the new ones and why you'd want to use them.  (It broke existing code and it wasn't obvious what I should be changing).

Anyway, there's not really a problem, so I'll close this.

Thanks for the library, it's been helpful.
